### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by KateJohnson** [UBC-MDS/seating_pref#10]
**Project setup:**
- The contributing document is very good and thorough, but it should be geared directed towards team members rather than the general public (unless you really do plan to maintain this project after the course is done. For example, will you use issues to track which components of the project team members are working on?

**Milestone 1:**
- For the student engagement questions, make it clear whether respondents should consider the MDS program in general and or a particular class/block.
- How will you use a linear model on a categorical outcome? But the analysis plan is otherwise very good.

**Comment by GeorgeJJW** [comment]
Thanks for the feedback!

I hope you enjoyed reading our proposal as much as we enjoyed drafting it.

We've added additional sections to the CONTRIBUTING.md file - #13.

We also adjusted our wording in the project proposal - #15 

Sorry that our survey was not really geared towards non-MDS students, we should have considered that when we created the wording of the survey questions :disappointed: .

Looking forward to your feedback next milestone.
