### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by blei7** [UBC-MDS/seating_pref#19]
Things that was well done:

-well detailed EDA
-great documentation

Things that might need some improvements:

-Since the sample size is pretty small, it might be more useful to overlap a jitters plot onto the box-plot so we can visualize the distributions between group.

-While detailed EDA is great, we think it could have been more concise overall

Suggestion for milestone 3:

overall great job and if anything, we think the overall report should be more concise.

**Comment by GeorgeJJW** [comment]
Thanks for the feedback @blei7!

I agree with your comments, and we are trying to be a lot more brief in the final report.
